### ISSUE TITLE
Bug: Getting weather by geolocation doesn't work

### ISSUE THREAD

**Issue by axeberg** [chas-academy/08-weather-app-Ardi83#1]
See gif below:
![geolocation](https://user-images.githubusercontent.com/343422/54805473-615fd380-4c77-11e9-99fe-6182f8b31b5d.gif)

**Comment by Ardi83** [comment]
@axelolsson I put recieving coordination at componentDidUpdate when you turn on geolocation , you should click one more time then state will update and show the information , i can put on componentDidMound , but i like this way . What do you think ?🙂

**Comment by Ardi83** [comment]
i added htaccess to redirect to https , thanks for comment
